### ISSUE TITLE
Underpopulation Dying Off Is Biggest Contributor to Shortlived Simulations

### ISSUE THREAD

**Issue by natis1** [natis1/openlife#3]
Overpopulation dying makes sense and stops the simulation from getting stupid, but underpopulation dying seems to lead to dead simulations.

Though with that being said it is best that underpopulated groups do not remain alive forever.

I think it is worth looking into ways to revive dying groups, or possibly create new groups from dying groups without it seeming unrealistic (edit and without randomness).

**Comment by LSaldyt** [comment]
I've tweaked some parameters so that underpopulation penalty is minimized by a faction of 10, and overpopulation penalty stays the same. I've also added a counter to keep track of how many cells currently exist.

**Comment by LSaldyt** [comment]
Underpopulation penalty has been further reduced by another factor of 10. If it continues to be a problem, I'll remove it entirely.

Additionally, the max_neighbors static constant allows for high birth rates between small groups of cells. This means that a cell will really only die of underpopulation if it is on its own. I think that we could consider the number of neighbors when making decisions on how the cell rotates, and this would give a realistic way to fix lonely cells. (Since lonely cells would seek out other cells)
